// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: vd_engine.proto

package vd_engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VdEngineService_DownloadVideoStream_FullMethodName = "/vd_engine.VdEngineService/DownloadVideoStream"
)

// VdEngineServiceClient is the client API for VdEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VdEngineServiceClient interface {
	DownloadVideoStream(ctx context.Context, in *DownloadVideoStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadVideoStreamResponse], error)
}

type vdEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVdEngineServiceClient(cc grpc.ClientConnInterface) VdEngineServiceClient {
	return &vdEngineServiceClient{cc}
}

func (c *vdEngineServiceClient) DownloadVideoStream(ctx context.Context, in *DownloadVideoStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadVideoStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VdEngineService_ServiceDesc.Streams[0], VdEngineService_DownloadVideoStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadVideoStreamRequest, DownloadVideoStreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VdEngineService_DownloadVideoStreamClient = grpc.ServerStreamingClient[DownloadVideoStreamResponse]

// VdEngineServiceServer is the server API for VdEngineService service.
// All implementations must embed UnimplementedVdEngineServiceServer
// for forward compatibility.
type VdEngineServiceServer interface {
	DownloadVideoStream(*DownloadVideoStreamRequest, grpc.ServerStreamingServer[DownloadVideoStreamResponse]) error
	mustEmbedUnimplementedVdEngineServiceServer()
}

// UnimplementedVdEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVdEngineServiceServer struct{}

func (UnimplementedVdEngineServiceServer) DownloadVideoStream(*DownloadVideoStreamRequest, grpc.ServerStreamingServer[DownloadVideoStreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadVideoStream not implemented")
}
func (UnimplementedVdEngineServiceServer) mustEmbedUnimplementedVdEngineServiceServer() {}
func (UnimplementedVdEngineServiceServer) testEmbeddedByValue()                         {}

// UnsafeVdEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VdEngineServiceServer will
// result in compilation errors.
type UnsafeVdEngineServiceServer interface {
	mustEmbedUnimplementedVdEngineServiceServer()
}

func RegisterVdEngineServiceServer(s grpc.ServiceRegistrar, srv VdEngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedVdEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VdEngineService_ServiceDesc, srv)
}

func _VdEngineService_DownloadVideoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadVideoStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VdEngineServiceServer).DownloadVideoStream(m, &grpc.GenericServerStream[DownloadVideoStreamRequest, DownloadVideoStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VdEngineService_DownloadVideoStreamServer = grpc.ServerStreamingServer[DownloadVideoStreamResponse]

// VdEngineService_ServiceDesc is the grpc.ServiceDesc for VdEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VdEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vd_engine.VdEngineService",
	HandlerType: (*VdEngineServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadVideoStream",
			Handler:       _VdEngineService_DownloadVideoStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vd_engine.proto",
}
